apiVersion: v1
kind: Deployment
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.7.02
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.7.02
    spec:
      containers:
      - name: myjavaapp-container
        image: maha4iac/mymahalogin:1
        ports:
        - containerPort: 8080