apiVersion: v1
kind: ReplicationController
metadata:
  name: nag-deploy
  labels:
    app: mydeploy
spec:
  replicas: 2
  selector:
    app: mydeploy 
    version: 2.7.01           # selector name and template of label must be same
  template:
    metadata:
      labels:
        app: mydeploy
        version: 2.7.01
    spec:
      containers:
      - name: naglogin
        image: maha4iac/mymahalogin:1
        ports:
        - containerport: 8080 